### ISSUE TITLE
Fails to build in travis occasionally 

### ISSUE THREAD

**Issue by fkaa** [rust-lang/bitflags#18] opened 2015-07-07 17:57 UTC
Looks very strange, sometimes it works, sometimes it doesn't:
* [Stable](https://travis-ci.org/gfx-rs/gfx/jobs/68552715)
* [Nightly](https://travis-ci.org/gfx-rs/gfx/jobs/69298955)
* [Most recent with nightly](https://travis-ci.org/gfx-rs/gfx/jobs/69920721)

Used to be:
```rust
Could not document `bitflags`.
Caused by:
  Process didn't exit successfully: `rustdoc /home/travis/.cargo/registry/src/github.com-0a35038f75765ae4/bitflags-0.2.1/src/lib.rs --crate-name bitflags -o /home/travis/build/gfx-rs/gfx/target/doc -L dependency=/home/travis/build/gfx-rs/gfx/target/debug/deps -L dependency=/home/travis/build/gfx-rs/gfx/target/debug/deps` (exit code: 101)
```
But has changed into this in the most recent build:
```rust
<bitflags macros>:7:27: 8:19 error: missing documentation for a constant
<bitflags macros>:7 $ ( # [ $ Flag_attr ] ) * pub const $ Flag : $ BitFlags = $ BitFlags {
<bitflags macros>:8 bits : $ value } ; ) + impl :: std:: fmt:: Debug for $ BitFlags {
<bitflags macros>:1:1: 77:67 note: in expansion of bitflags!
/home/travis/.cargo/registry/src/github.com-0a35038f75765ae4/draw_state-0.1.1/src/state.rs:289:1: 299:3 note: expansion site
/home/travis/.cargo/registry/src/github.com-0a35038f75765ae4/draw_state-0.1.1/src/lib.rs:17:9: 17:21 note: lint level defined here
/home/travis/.cargo/registry/src/github.com-0a35038f75765ae4/draw_state-0.1.1/src/lib.rs:17 #![deny(missing_docs, missing_copy_implementations)]
                                                                                                    ^~~~~~~~~~~~
<bitflags macros>:7:27: 8:19 error: missing documentation for a constant
<bitflags macros>:7 $ ( # [ $ Flag_attr ] ) * pub const $ Flag : $ BitFlags = $ BitFlags {
<bitflags macros>:8 bits : $ value } ; ) + impl :: std:: fmt:: Debug for $ BitFlags {
<bitflags macros>:1:1: 77:67 note: in expansion of bitflags!
/home/travis/.cargo/registry/src/github.com-0a35038f75765ae4/draw_state-0.1.1/src/state.rs:289:1: 299:3 note: expansion site
/home/travis/.cargo/registry/src/github.com-0a35038f75765ae4/draw_state-0.1.1/src/lib.rs:17:9: 17:21 note: lint level defined here
/home/travis/.cargo/registry/src/github.com-0a35038f75765ae4/draw_state-0.1.1/src/lib.rs:17 #![deny(missing_docs, missing_copy_implementations)]
                                                                                                    ^~~~~~~~~~~~
<bitflags macros>:7:27: 8:19 error: missing documentation for a constant
<bitflags macros>:7 $ ( # [ $ Flag_attr ] ) * pub const $ Flag : $ BitFlags = $ BitFlags {
<bitflags macros>:8 bits : $ value } ; ) + impl :: std:: fmt:: Debug for $ BitFlags {
<bitflags macros>:1:1: 77:67 note: in expansion of bitflags!
/home/travis/.cargo/registry/src/github.com-0a35038f75765ae4/draw_state-0.1.1/src/state.rs:289:1: 299:3 note: expansion site
/home/travis/.cargo/registry/src/github.com-0a35038f75765ae4/draw_state-0.1.1/src/lib.rs:17:9: 17:21 note: lint level defined here
/home/travis/.cargo/registry/src/github.com-0a35038f75765ae4/draw_state-0.1.1/src/lib.rs:17 #![deny(missing_docs, missing_copy_implementations)]
                                                                                                    ^~~~~~~~~~~~
<bitflags macros>:7:27: 8:19 error: missing documentation for a constant
<bitflags macros>:7 $ ( # [ $ Flag_attr ] ) * pub const $ Flag : $ BitFlags = $ BitFlags {
<bitflags macros>:8 bits : $ value } ; ) + impl :: std:: fmt:: Debug for $ BitFlags {
<bitflags macros>:1:1: 77:67 note: in expansion of bitflags!
/home/travis/.cargo/registry/src/github.com-0a35038f75765ae4/draw_state-0.1.1/src/state.rs:289:1: 299:3 note: expansion site
/home/travis/.cargo/registry/src/github.com-0a35038f75765ae4/draw_state-0.1.1/src/lib.rs:17:9: 17:21 note: lint level defined here
/home/travis/.cargo/registry/src/github.com-0a35038f75765ae4/draw_state-0.1.1/src/lib.rs:17 #![deny(missing_docs, missing_copy_implementations)]
                                                                                                    ^~~~~~~~~~~~
<bitflags macros>:7:27: 8:19 error: missing documentation for a constant
<bitflags macros>:7 $ ( # [ $ Flag_attr ] ) * pub const $ Flag : $ BitFlags = $ BitFlags {
<bitflags macros>:8 bits : $ value } ; ) + impl :: std:: fmt:: Debug for $ BitFlags {
<bitflags macros>:1:1: 77:67 note: in expansion of bitflags!
/home/travis/.cargo/registry/src/github.com-0a35038f75765ae4/draw_state-0.1.1/src/state.rs:289:1: 299:3 note: expansion site
/home/travis/.cargo/registry/src/github.com-0a35038f75765ae4/draw_state-0.1.1/src/lib.rs:17:9: 17:21 note: lint level defined here
/home/travis/.cargo/registry/src/github.com-0a35038f75765ae4/draw_state-0.1.1/src/lib.rs:17 #![deny(missing_docs, missing_copy_implementations)]
                                                                                                    ^~~~~~~~~~~~
<bitflags macros>:7:27: 8:19 error: missing documentation for a constant
<bitflags macros>:7 $ ( # [ $ Flag_attr ] ) * pub const $ Flag : $ BitFlags = $ BitFlags {
<bitflags macros>:8 bits : $ value } ; ) + impl :: std:: fmt:: Debug for $ BitFlags {
<bitflags macros>:1:1: 77:67 note: in expansion of bitflags!
/home/travis/.cargo/registry/src/github.com-0a35038f75765ae4/draw_state-0.1.1/src/state.rs:289:1: 299:3 note: expansion site
/home/travis/.cargo/registry/src/github.com-0a35038f75765ae4/draw_state-0.1.1/src/lib.rs:17:9: 17:21 note: lint level defined here
/home/travis/.cargo/registry/src/github.com-0a35038f75765ae4/draw_state-0.1.1/src/lib.rs:17 #![deny(missing_docs, missing_copy_implementations)]
                                                                                                    ^~~~~~~~~~~~
<bitflags macros>:7:27: 8:19 error: missing documentation for a constant
<bitflags macros>:7 $ ( # [ $ Flag_attr ] ) * pub const $ Flag : $ BitFlags = $ BitFlags {
<bitflags macros>:8 bits : $ value } ; ) + impl :: std:: fmt:: Debug for $ BitFlags {
<bitflags macros>:1:1: 77:67 note: in expansion of bitflags!
/home/travis/.cargo/registry/src/github.com-0a35038f75765ae4/draw_state-0.1.1/src/target.rs:43:1: 54:3 note: expansion site
/home/travis/.cargo/registry/src/github.com-0a35038f75765ae4/draw_state-0.1.1/src/lib.rs:17:9: 17:21 note: lint level defined here
/home/travis/.cargo/registry/src/github.com-0a35038f75765ae4/draw_state-0.1.1/src/lib.rs:17 #![deny(missing_docs, missing_copy_implementations)]
                                                                                                    ^~~~~~~~~~~~
<bitflags macros>:7:27: 8:19 error: missing documentation for a constant
<bitflags macros>:7 $ ( # [ $ Flag_attr ] ) * pub const $ Flag : $ BitFlags = $ BitFlags {
<bitflags macros>:8 bits : $ value } ; ) + impl :: std:: fmt:: Debug for $ BitFlags {
<bitflags macros>:1:1: 77:67 note: in expansion of bitflags!
/home/travis/.cargo/registry/src/github.com-0a35038f75765ae4/draw_state-0.1.1/src/target.rs:43:1: 54:3 note: expansion site
/home/travis/.cargo/registry/src/github.com-0a35038f75765ae4/draw_state-0.1.1/src/lib.rs:17:9: 17:21 note: lint level defined here
/home/travis/.cargo/registry/src/github.com-0a35038f75765ae4/draw_state-0.1.1/src/lib.rs:17 #![deny(missing_docs, missing_copy_implementations)]
                                                                                                    ^~~~~~~~~~~~
<bitflags macros>:7:27: 8:19 error: missing documentation for a constant
<bitflags macros>:7 $ ( # [ $ Flag_attr ] ) * pub const $ Flag : $ BitFlags = $ BitFlags {
<bitflags macros>:8 bits : $ value } ; ) + impl :: std:: fmt:: Debug for $ BitFlags {
<bitflags macros>:1:1: 77:67 note: in expansion of bitflags!
/home/travis/.cargo/registry/src/github.com-0a35038f75765ae4/draw_state-0.1.1/src/target.rs:43:1: 54:3 note: expansion site
/home/travis/.cargo/registry/src/github.com-0a35038f75765ae4/draw_state-0.1.1/src/lib.rs:17:9: 17:21 note: lint level defined here
/home/travis/.cargo/registry/src/github.com-0a35038f75765ae4/draw_state-0.1.1/src/lib.rs:17 #![deny(missing_docs, missing_copy_implementations)]
                                                                                                    ^~~~~~~~~~~~
<bitflags macros>:7:27: 8:19 error: missing documentation for a constant
<bitflags macros>:7 $ ( # [ $ Flag_attr ] ) * pub const $ Flag : $ BitFlags = $ BitFlags {
<bitflags macros>:8 bits : $ value } ; ) + impl :: std:: fmt:: Debug for $ BitFlags {
<bitflags macros>:1:1: 77:67 note: in expansion of bitflags!
/home/travis/.cargo/registry/src/github.com-0a35038f75765ae4/draw_state-0.1.1/src/target.rs:43:1: 54:3 note: expansion site
/home/travis/.cargo/registry/src/github.com-0a35038f75765ae4/draw_state-0.1.1/src/lib.rs:17:9: 17:21 note: lint level defined here
/home/travis/.cargo/registry/src/github.com-0a35038f75765ae4/draw_state-0.1.1/src/lib.rs:17 #![deny(missing_docs, missing_copy_implementations)]
                                                                                                    ^~~~~~~~~~~~
<bitflags macros>:7:27: 8:19 error: missing documentation for a constant
<bitflags macros>:7 $ ( # [ $ Flag_attr ] ) * pub const $ Flag : $ BitFlags = $ BitFlags {
<bitflags macros>:8 bits : $ value } ; ) + impl :: std:: fmt:: Debug for $ BitFlags {
<bitflags macros>:1:1: 77:67 note: in expansion of bitflags!
/home/travis/.cargo/registry/src/github.com-0a35038f75765ae4/draw_state-0.1.1/src/target.rs:43:1: 54:3 note: expansion site
/home/travis/.cargo/registry/src/github.com-0a35038f75765ae4/draw_state-0.1.1/src/lib.rs:17:9: 17:21 note: lint level defined here
/home/travis/.cargo/registry/src/github.com-0a35038f75765ae4/draw_state-0.1.1/src/lib.rs:17 #![deny(missing_docs, missing_copy_implementations)]
                                                                                                    ^~~~~~~~~~~~
<bitflags macros>:7:27: 8:19 error: missing documentation for a constant
<bitflags macros>:7 $ ( # [ $ Flag_attr ] ) * pub const $ Flag : $ BitFlags = $ BitFlags {
<bitflags macros>:8 bits : $ value } ; ) + impl :: std:: fmt:: Debug for $ BitFlags {
<bitflags macros>:1:1: 77:67 note: in expansion of bitflags!
/home/travis/.cargo/registry/src/github.com-0a35038f75765ae4/draw_state-0.1.1/src/target.rs:43:1: 54:3 note: expansion site
/home/travis/.cargo/registry/src/github.com-0a35038f75765ae4/draw_state-0.1.1/src/lib.rs:17:9: 17:21 note: lint level defined here
/home/travis/.cargo/registry/src/github.com-0a35038f75765ae4/draw_state-0.1.1/src/lib.rs:17 #![deny(missing_docs, missing_copy_implementations)]
                                                                                                    ^~~~~~~~~~~~
<bitflags macros>:7:27: 8:19 error: missing documentation for a constant
<bitflags macros>:7 $ ( # [ $ Flag_attr ] ) * pub const $ Flag : $ BitFlags = $ BitFlags {
<bitflags macros>:8 bits : $ value } ; ) + impl :: std:: fmt:: Debug for $ BitFlags {
<bitflags macros>:1:1: 77:67 note: in expansion of bitflags!
/home/travis/.cargo/registry/src/github.com-0a35038f75765ae4/draw_state-0.1.1/src/target.rs:43:1: 54:3 note: expansion site
/home/travis/.cargo/registry/src/github.com-0a35038f75765ae4/draw_state-0.1.1/src/lib.rs:17:9: 17:21 note: lint level defined here
/home/travis/.cargo/registry/src/github.com-0a35038f75765ae4/draw_state-0.1.1/src/lib.rs:17 #![deny(missing_docs, missing_copy_implementations)]
                                                                                                    ^~~~~~~~~~~~
<bitflags macros>:7:27: 8:19 error: missing documentation for a constant
<bitflags macros>:7 $ ( # [ $ Flag_attr ] ) * pub const $ Flag : $ BitFlags = $ BitFlags {
<bitflags macros>:8 bits : $ value } ; ) + impl :: std:: fmt:: Debug for $ BitFlags {
<bitflags macros>:1:1: 77:67 note: in expansion of bitflags!
<bitflags macros>:75:1: 77:63 note: expansion site
<bitflags macros>:1:1: 77:67 note: in expansion of bitflags!
/home/travis/.cargo/registry/src/github.com-0a35038f75765ae4/draw_state-0.1.1/src/target.rs:56:1: 62:3 note: expansion site
/home/travis/.cargo/registry/src/github.com-0a35038f75765ae4/draw_state-0.1.1/src/lib.rs:17:9: 17:21 note: lint level defined here
/home/travis/.cargo/registry/src/github.com-0a35038f75765ae4/draw_state-0.1.1/src/lib.rs:17 #![deny(missing_docs, missing_copy_implementations)]
                                                                                                    ^~~~~~~~~~~~
<bitflags macros>:7:27: 8:19 error: missing documentation for a constant
<bitflags macros>:7 $ ( # [ $ Flag_attr ] ) * pub const $ Flag : $ BitFlags = $ BitFlags {
<bitflags macros>:8 bits : $ value } ; ) + impl :: std:: fmt:: Debug for $ BitFlags {
<bitflags macros>:1:1: 77:67 note: in expansion of bitflags!
<bitflags macros>:75:1: 77:63 note: expansion site
<bitflags macros>:1:1: 77:67 note: in expansion of bitflags!
/home/travis/.cargo/registry/src/github.com-0a35038f75765ae4/draw_state-0.1.1/src/target.rs:56:1: 62:3 note: expansion site
/home/travis/.cargo/registry/src/github.com-0a35038f75765ae4/draw_state-0.1.1/src/lib.rs:17:9: 17:21 note: lint level defined here
/home/travis/.cargo/registry/src/github.com-0a35038f75765ae4/draw_state-0.1.1/src/lib.rs:17 #![deny(missing_docs, missing_copy_implementations)]
                                                                                                    ^~~~~~~~~~~~
error: aborting due to 15 previous errors
Build failed, waiting for other jobs to finish...
Could not compile `draw_state`.
Caused by:
  Process didn't exit successfully: `rustc /home/travis/.cargo/registry/src/github.com-0a35038f75765ae4/draw_state-0.1.1/src/lib.rs --crate-name draw_state --crate-type lib -g -C metadata=db41f6c0c53c3a65 -C extra-filename=-db41f6c0c53c3a65 --out-dir /home/travis/build/gfx-rs/gfx/target/debug/deps --emit=dep-info,link -L dependency=/home/travis/build/gfx-rs/gfx/target/debug/deps -L dependency=/home/travis/build/gfx-rs/gfx/target/debug/deps --extern bitflags=/home/travis/build/gfx-rs/gfx/target/debug/deps/libbitflags-425420435a0b4460.rlib -Awarnings` (exit code: 101)
```

**Comment by alexcrichton** [comment] 2015-07-07 18:16
This is because the constants aren't documented, and `#[deny(missing_docs)]` is generating an error as a result. Looks like it's all working as intended, though, so closing.

**Closed by alexcrichton** 2015-07-07 18:16 UTC

**Comment by fkaa** [comment] 2015-07-07 18:23
Shouldn't [this line](https://github.com/gfx-rs/draw_state/blob/master/src/state.rs#L290) override that?

**Comment by alexcrichton** [comment] 2015-07-07 18:25
No it doesn't apply those attributes to all constants, just the struct itself.

**Comment by fkaa** [comment] 2015-07-08 22:28
@alexcrichton Fixed the build errors in `draw_state`, but now I'm getting a problem which seems to be bitflags related: https://travis-ci.org/gfx-rs/gfx/jobs/70136948
```rust
Could not document `bitflags`.
Caused by:
  Process didn't exit successfully: `rustdoc /home/travis/.cargo/registry/src/github.com-0a35038f75765ae4/bitflags-0.3.2/src/lib.rs --crate-name bitflags -o /home/travis/build/gfx-rs/gfx/target/doc -L dependency=/home/travis/build/gfx-rs/gfx/target/debug/deps -L dependency=/home/travis/build/gfx-rs/gfx/target/debug/deps` (exit code: 101)
--- stderr
thread '<unnamed>' panicked at 'failed to generate documentation: File exists (os error 17)', ../src/librustdoc/lib.rs:293
thread '<main>' panicked at 'called `Result::unwrap()` on an `Err` value: Any', ../src/libcore/result.rs:731
```

**Comment by alexcrichton** [comment] 2015-07-08 23:34
That looks like it may be a bug in rustdoc?
